name: IINACT build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Download Dalamud
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/stg/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip /tmp/dalamud
    - name: Build
      run: dotnet build -c release
    - name: Prepare Build Artifact
      shell: pwsh
      run: |
        Copy-Item "IINACT/bin/Release/win-x64/IINACT/latest.zip" -Destination "IINACT.zip"
        Expand-Archive -Force IINACT.zip Artifact
    - name: Upload IINACT
      uses: actions/upload-artifact@v4
      with:
        name: IINACT
        path: Artifact/*
